hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986"

[[files]]
file = "config/betterf3.json"
hash = "4e41dfc84047d92a645d9ca3c0ddf06036277ca739d85fbabc5c75ba11886f2d"

[[files]]
file = "config/blur.json"
hash = "c118f7ab0baf116aac0ef53bdf65e4c5446054b6fd84d53f2a24ac04452d1288"

[[files]]
file = "config/borderlessmining.json"
hash = "97d88071650e42b4c23540a24de6c7d5d72febd593efd33f7290a9352c169cfe"

[[files]]
file = "config/capes.json5"
hash = "26f7730b69277b55dc6346922a581b76375bb6166e0b132e4539f26cccf059aa"

[[files]]
file = "config/citresewn.json"
hash = "1ea03400477ac2075d61ae58cfc573bc78ce954507d090ab69547de279918656"

[[files]]
file = "config/craftpresence.properties"
hash = "39396d62371c87eac0358069c48eda8ba1a6732594e57205781316277d151780"

[[files]]
file = "config/custom-hud/config.json"
hash = "d3edcc8cc6e1a965fd20ee116dcfffdb4f940abf89fa11584c05817bb2d1fc2f"

[[files]]
file = "config/custom-hud/profile1.txt"
hash = "4e8c19658f462cc3b86cd8ae8ea68c6cfadb73dc1c03b12533d2178efcfaffa8"

[[files]]
file = "config/custom-hud/profile2.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/custom-hud/profile3.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/emi.css"
hash = "6cbfcf74a41d25de57e61aef6bcfab095205e066ced283ebee5e18bad98af31a"

[[files]]
file = "config/entity_texture_features.json"
hash = "33b748f82416aa3401dbb7e19320e67912c85ead42d42f11fc925fc4e0d7390c"

[[files]]
file = "config/entityculling.json"
hash = "0c78e42bc9ee8629e05830c89b882382dfa24c772c9b5a16d91225e1c63b11ad"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "f67a43608640547ffc870307cf8e92e4d6ef303971e71ea9b9fde475577cf24b"

[[files]]
file = "config/iris.properties"
hash = "0430b83e0962a1c5726c507e2771112af64badeb010c49638e2e717bce0ecfab"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "cbe3787709fcf42fa9f0c4dcf5feff2b61e0b47dc8373b82294db2f7adb7003a"

[[files]]
file = "config/ok_zoomer/config.toml"
hash = "b1580e4110e8413196a6ecf56bffda26e2a60afe3515e7e0653aafb0d30c5675"

[[files]]
file = "config/puzzle.json"
hash = "b562484e864d9d2f28e1dbded720cff7ada38a252f9234a2a0e22353c0032b77"

[[files]]
file = "config/sodium-extra-options.json"
hash = "8b6e02b5060fc52fb01f2eb486ad3b995129084aea2b53e4416125323757880e"

[[files]]
file = "config/sodium-options.json"
hash = "52fa21d31fc7a3f71311430a38f783f63923ebe84fc19823b7a5c2a087a45cf7"

[[files]]
file = "config/yosbr/options.txt"
hash = "de7e51696e9df0dd887c7525222de80608dd4884203d0166b3979caa3f57cb4c"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "fbad3ce2bcab1b8a73a541000100dc5ed3323bcf571e4e2a4a3c28db5c520509"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "813c9e3195948559d0daeb5a03ac0169645719c01a9604bebc61ae71d03525a0"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "73386e4a41baab1188f2c594ac9efad42ccbb3c02934d21cc86461b616121954"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "242e18d68cb8d218df43e713e97239631f8612384789068659c4898cfa49fcef"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4d571d5ebe245ffb62a0df83e81d1c03670807d3528650d6dd9c983bd26ae860"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "bc08ed290f7c076e8297b38f80af9694aa5972318ef29a99693a3e297b76f386"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "fada6c5111be510ce9dcda58588edd0d694e11bc040fcc2afe0586e8560abb49"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "c59209e703e553f58306aa1a66dc30a58476f89ad2d40da540508dc72fe0311f"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "757207131774e618e46c6c0ad407c8ba7c45d3c9c4fb59ffa8209d1bfe04a0d8"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "5e206d6a7aa7744a3322189386a7e3c4315df2dd8a1d3a648bcde498a7a3c934"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "97b90825ea397eae1dc108b5a9257e3065feacb553e72c019fba62495a72c1d0"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "309fa9d0ab190059d9a13933db512f36f01ec0b40f37fa6e919ec085c686df9e"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "407fd025c6912135c7d40c238bb96fe05ea8172c403a100ed86f978fc8124c81"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "eaba2f41f04c306118190beb2a2bf4a44263e0196a106b9c8a9bfddff038afab"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "0da3b33d0d62fcaf24835fb432b8dd9be02e82897cd43fddc38fa81106203d37"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "379a2c793f5f3f31b06581ba86de7ae4f32f401b466fb4dd684d6a7596df2fbf"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "1a4c9d83b0709fd2f91814eb67f81e19bb1493315c42cb65efe911d0f34c5a13"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "213cad77d46ff46fe20780b01856cb1a8812747e9c3564203669bf3905e646e2"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "c49d1423a5f2563335fd5719862a861c8ae2c9cbc46598e767c3e2fe1042ecae"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "3648ed55ffae5bc153c16b2d414925cc30165b5171aa0e2a146e5ba22366fcf1"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "314e9f91c9c12ca48ec8a1b1e5c9b5d3da08bd1035af6a63db011c5419644df9"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c06e098c6d6eda6da4492e4a8dff1796e6081bbd30f487ffb89e1ed3c485e805"
metafile = true

[[files]]
file = "mods/customhud.pw.toml"
hash = "e9cf2b18d2bdf4a169550920a821ce261a7fbaafccd82e0aac7276113832787d"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "59da146d66e2948dfbd203684937dfb822711a228bd505332b5a979678bedbbc"
metafile = true

[[files]]
file = "mods/draggable-resource-packs.pw.toml"
hash = "6e94a2241d03fff4d1eef01a82f161f741a76bc61d02ead1dcfeda76e84a815b"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "f52293cc81b07666eeee3bfcf5f34039e2d2bc64cd22416b5cbdb554eec17a0e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "855e5f89a1c2d225f10927dd9bdd06aaffbc0c59b6d2c525460db6f1c9742ad5"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "7250c341106f7097064eaf65f72cb3d7668f0c3a28a67278442f42441020d465"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "76a5d61442e06180aede0b5cf457f04b471b37d85a8631726d550f9309b2ddeb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "76f23e3c7d290c587085b22f59e06160a38593d73859cbb4a4738d1fa2fade4d"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "0b0b7d2de5e46b9032ae84b25f554839e7fabfeab7bd8bcb48392b940e112f38"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "f0a1c212e68166b823a68080b32fd27d772fe87d533409fc0feb35a5c4c2093e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/gatekeep.pw.toml"
hash = "8521ea1ccd72edafd5eb3288f132d05ef67dcb90c930b573ac41b1fb16d8516a"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.pw.toml"
hash = "4191daf9db203945cd504e0489ce9008f718bb69fa8ce36cf3847ab28f05355c"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "b78af3bf0642db40d9295d6228eaa65065414de18995f84970b6e1698e93aced"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "3f196a5ba67e18f52901014dd413376944faf11cbf2f35722a08ac6195dd363d"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c3abf99ceae59c52190eff3132d949073ef39594ce38a0e90a98eca835a0efc4"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "b893248407cbc155a5182b151acf50df075cef08bd0a9470c222425e8e47a809"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "dadcde5442ffdd9755166893fbf6985409908d469a557788301523c16c6e6ebc"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "0ab0925b9d00ddcf75dc5077fba4eee2c825945a7590750e1821ba783fb26f37"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "e02f0d0b8bf9a5a62bd10d41ddf02e405151ebd9085b0ca955f9d2f903d2a459"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7cc268ba8c316a732881e631e00db7cf8db0891f24155475db0a4e88840cdfe8"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4716789e4a806c1cabcef27e67150215edb4c3d737e9a87d90f2f615d6c196cd"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "1946f660ed8f0b6b4fa1680fbc14f30a0db503b09fac5ffd0635ecd9cfecf6d1"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "c7388b6ebb78040be98251fb064a009f3d7574133e15d2844e3fadf2929b2980"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "1199295c714f62bbb8eeb2f70ab72a5f21482b71bfb6601829248d9c588138e0"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "24b56cdea0d96fc1b03b8cb6e6bb4b600c6fe730f7cd86e84004d100779ad5a1"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "d1558ff187abe468110fef11eee834aa3c03df732e706ac16e221425b538da4d"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "8f554f10f3ca26505c1f51871263a7d75fca1e07a288c60c1a96b18f830beede"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "8c66464e7a6c353ef3b8572c835c6e77dbfb48c872e399d9677838f06616b0ee"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "cd2704a99b24207489be8c2b19167e04e241fc4385985fbb3761eda1ed92d26f"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "8cc78f5916f31b9d350f75d5fd0dad8df9662066763324b36abf6eaced24aef5"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "fc829d9bfa6e9c399324e64cc5feb01f01630fc0971c7286ac08b5575dcf89b2"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "48aefe7fedf925380793a244646e6449cf3f5aebeeb651b09ab86d6638e8b0c1"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "997b1a93ccd70d86710170532e27b301cd15723fd7e8e74a14d8322ce5d47dd7"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.pw.toml"
hash = "2e814a41e25a222c3d0363931887da7b8c63522281a7044a21dda255f8318b5e"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "014566a9d16177ef1499864718b28090b5ac254e3e910a2cea67b911b56f3e5a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1c6d01b013b9e8c6dd921046adc7c7768814c17a0fde45cbe695c8e2de40f8be"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "79721c68c3475400efab4fc288cc27e13d4337f649e1ca09527258c5abb49c52"
metafile = true

[[files]]
file = "mods/roundaround-axolotl-buckets.pw.toml"
hash = "af4a3b3293422552cbc310bc7c83b99e1d8b4228a195b43294d257fd62208088"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "8cee882d886709a92b1c2ba19e6c5d1a55da9cc6ed79b78d62eec98b5b768588"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "99c83e926faf4565a4a75f8666a9c68721c3effdeece027509e23c5d50395321"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/statuseffecttimer.pw.toml"
hash = "1da5f38d24b00e49108dedf43fe3dd388bade82563e5f69689d051167ea57927"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "e4d8df8da89afc27ef4066bf63fb258fdef9bb367498372a6e5833dda27e0765"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "f890affbc81dd0b392971738eb723aae198b554be6439feb6fa819ebdf7ba975"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "de08ce31ccfbd64fb308ddb0d1076d4e6cd65ac43bd6a16e57e01a1d14336428"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f1b822298ccbb96ab43b054811b802080c3160db2168e7c795370779e8bc1b93"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true
